In [18]:
import pandas as pd
import json
import numpy as np

box_office = pd.read_json("box_office.json")

box_office

,url,ranks,film_titles,film_links,worldwide_gross,domestic_gross,foreign_gross
0,https://www.boxofficemojo.com/year/world/2010/,"[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14...","[Toy Story 3, Alice in Wonderland, Harry Potte...",[/releasegroup/gr87839237/?ref_=bo_ydw_table_1...,"[$1,066,969,703, $1,025,467,110, $960,283,305,...","[$415,004,880, $334,191,110, $295,983,305, $29...","[$651,964,823, $691,276,000, $664,300,000, $53..."
1,https://www.boxofficemojo.com/year/world/2014/,"[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14...","[Transformers: Age of Extinction, The Hobbit: ...",[/releasegroup/gr41374213/?ref_=bo_ydw_table_1...,"[$1,104,054,072, $956,019,788, $772,776,600, $...","[$245,439,076, $255,119,788, $333,176,600, $24...","[$858,614,996, $700,900,000, $439,600,000, $51..."
2,https://www.boxofficemojo.com/year/world/2013/,"[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14...","[Frozen, Iron Man 3, Despicable Me 2, The Hobb...",[/releasegroup/gr1177113093/?ref_=bo_ydw_table...,"[$1,280,802,282, $1,214,811,252, $970,766,005,...","[$400,738,009, $409,013,994, $368,065,385, $25...","[$880,064,273, $805,797,258, $602,700,620, $70..."
3,https://www.boxofficemojo.com/year/world/2016/,"[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14...","[Captain America: Civil War, Rogue One: A Star...",[/releasegroup/gr2136297989/?ref_=bo_ydw_table...,"[$1,153,296,293, $1,056,057,273, $1,028,570,88...","[$408,084,349, $532,177,324, $486,295,561, $34...","[$745,211,944, $523,879,949, $542,275,328, $68..."
4,https://www.boxofficemojo.com/year/world/2015/,"[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14...","[Star Wars: Episode VII - The Force Awakens, J...",[/releasegroup/gr3305984517/?ref_=bo_ydw_table...,"[$2,068,223,624, $1,670,400,637, $1,515,047,67...","[$936,662,225, $652,270,625, $353,007,020, $45...","[$1,131,561,399, $1,018,130,012, $1,162,040,65..."
5,https://www.boxofficemojo.com/year/world/2018/,"[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14...","[Avengers: Infinity War, Black Panther, Jurass...",[/releasegroup/gr3915469317/?ref_=bo_ydw_table...,"[$2,048,359,754, $1,346,913,161, $1,308,467,94...","[$678,815,482, $700,059,566, $417,719,760, $60...","[$1,369,544,272, $646,853,595, $890,748,184, $..."
6,https://www.boxofficemojo.com/year/world/2011/,"[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14...","[Harry Potter and the Deathly Hallows: Part 2,...",[/releasegroup/gr2033603077/?ref_=bo_ydw_table...,"[$1,341,511,219, $1,123,794,079, $1,045,713,80...","[$381,011,219, $352,390,543, $241,071,802, $28...","[$960,500,000, $771,403,536, $804,642,000, $43..."
7,https://www.boxofficemojo.com/year/world/2017/,"[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14...","[Star Wars: Episode VIII - The Last Jedi, Beau...",[/releasegroup/gr3764736517/?ref_=bo_ydw_table...,"[$1,332,539,889, $1,263,521,126, $1,236,005,11...","[$620,181,382, $504,014,165, $226,008,385, $26...","[$712,358,507, $759,506,961, $1,009,996,733, $..."
8,https://www.boxofficemojo.com/year/world/2025/,"[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14...","[Captain America: Brave New World, Dog Man, Br...",[/releasegroup/gr2894942725/?ref_=bo_ydw_table...,"[$293,999,575, $105,541,330, $66,212,000, $56,...","[$145,631,098, $79,369,330, -, $36,015,016, $4...","[$148,368,477, $26,172,000, $66,212,000, $20,5..."
9,https://www.boxofficemojo.com/year/world/2020/,"[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14...",[Demon Slayer: Kimetsu no Yaiba - The Movie: M...,[/releasegroup/gr2409976325/?ref_=bo_ydw_table...,"[$473,230,408, $461,421,559, $426,505,244, $42...","[$49,505,008, $372,755, $206,305,244, -, $58,5...","[$423,725,400, $461,048,804, $220,200,000, $42..."
10,https://www.boxofficemojo.com/year/world/2021/,"[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14...","[Spider-Man: No Way Home, The Battle at Lake C...",[/releasegroup/gr3957150213/?ref_=bo_ydw_table...,"[$1,910,982,770, $902,548,476, $822,009,764, $...","[$804,793,477, $342,411, -, $160,891,007, $173...","[$1,106,189,293, $902,206,065, $822,009,764, $..."
11,https://www.boxofficemojo.com/year/world/2012/,"[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14...","[The Avengers, Skyfall, The Dark Knight Rises,...",[/releasegroup/gr1911837189/?ref_=bo_ydw_table...,"[$1,518,812,988, $1,108,561,013, $1,084,939,09...","[$623,357,910, $304,360,277, $448,139,099, $30...","[$895,455,078, $804,200,736, $636,800,000, $71..."
12,https://www.boxofficemojo.com/year/world/2024/,"[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14...","[Inside Out 2, Deadpool & Wolverine, Moana 2, ...",[/releasegroup/gr2474856965/?ref_=bo_ydw_table...,"[$1,698,863,816, $1,338,073,645, $1,053,502,48...","[$652,980,194, $636,745,858, $458,890,613, $36...","[$1,045,883,622, $701,327,787, $594,611,867, $..."
13,https://www.boxofficemojo.com/year/world/2019/,"[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14...","[Avengers: Endgame, The Lion King, Frozen II, ...",[/releasegroup/gr3511898629/?ref_=bo_ydw_table...,"[$2,799,439,100, $1,656,943,394, $1,450,026,93...","[$858,373,000, $543,638,043, $477,373,578, $39...","[$1,941,066,100, $1,113,305,351, $972,653,355,..."
14,https://www.boxofficemojo.com/year/world/2022/,"[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14...","[Avatar: The Way of Water, Top Gun: Maverick, ...",[/releasegroup/gr1943818757/?ref_=bo_ydw_table...,"[$2,320,250,281, $1,495,696,292, $1,001,978,08...","[$684,075,767, $718,732,821, $376,851,080, $41...","[$1,636,174,514, $776,963,471, $625,127,000, $..."
15,https://www.boxofficemojo.com/year/world/2023/,"[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14...","[Barbie, The Super Mario Bros. Movie, Oppenhei...",[/releasegroup/gr629756421/?ref_=bo_ydw_table_...,"[$1,447,038,421, $1,360,847,665, $975,594,978,...","[$636,238,421, $574,934,330, $329,862,540, $35...","[$810,800,000, $785,913,335, $645,732,438, $48..."

In [23]:
box_office_exploded = box_office.explode(["ranks", "film_titles", "film_links", "worldwide_gross", "domestic_gross", "foreign_gross"])

box_office_exploded.columns = ["url", "rank", "title", "link", "worldwide_gross", "domestic_gross", "foreign_gross"]

for col in ["worldwide_gross", "domestic_gross", "foreign_gross"]:
    box_office_exploded[col] = box_office_exploded[col].apply(lambda x: x.replace("$", "").replace(",", "")).replace("-", np.nan).astype(float)

box_office_exploded

,url,rank,title,link,worldwide_gross,domestic_gross,foreign_gross
0,https://www.boxofficemojo.com/year/world/2010/,1,Toy Story 3,/releasegroup/gr87839237/?ref_=bo_ydw_table_1,1.066970e+09,415004880.0,651964823.0
0,https://www.boxofficemojo.com/year/world/2010/,2,Alice in Wonderland,/releasegroup/gr1992577541/?ref_=bo_ydw_table_2,1.025467e+09,334191110.0,691276000.0
0,https://www.boxofficemojo.com/year/world/2010/,3,Harry Potter and the Deathly Hallows: Part 1,/releasegroup/gr1728664069/?ref_=bo_ydw_table_3,9.602833e+08,295983305.0,664300000.0
0,https://www.boxofficemojo.com/year/world/2010/,4,Inception,/releasegroup/gr1400852997/?ref_=bo_ydw_table_4,8.282587e+08,292576195.0,535682500.0
0,https://www.boxofficemojo.com/year/world/2010/,5,Shrek Forever After,/releasegroup/gr2889241093/?ref_=bo_ydw_table_5,7.526009e+08,238736787.0,513864080.0
...,...,...,...,...,...,...,...
15,https://www.boxofficemojo.com/year/world/2023/,196,Sun and Concrete,/releasegroup/gr2879083013/?ref_=bo_ydw_table_196,1.012034e+07,NaN,10120340.0
15,https://www.boxofficemojo.com/year/world/2023/,197,Cobweb,/releasegroup/gr2560250373/?ref_=bo_ydw_table_197,1.009182e+07,NaN,10091821.0
15,https://www.boxofficemojo.com/year/world/2023/,198,The Peasants,/releasegroup/gr3566359045/?ref_=bo_ydw_table_198,1.006435e+07,155188.0,9909159.0
15,https://www.boxofficemojo.com/year/world/2023/,199,Talk to Her Undated France Release,/releasegroup/gr1543197189/?ref_=bo_ydw_table_199,9.550733e+06,NaN,9549770.0
15,https://www.boxofficemojo.com/year/world/2023/,200,Kandahar,/releasegroup/gr3934540293/?ref_=bo_ydw_table_200,9.387311e+06,4813132.0,4574179.0